WebApplication2/Models/DatabaseContext.cs
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    public class DatabaseContext:DbContext
    {
        public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options)
        {

        }
       
      /*  public DbSet<User>Users { get; set; }*/

        public DbSet<Item>products { get; set; }
      
    }
}

WebApplication2/Models/ErrorViewModel.cs
namespace WebApplication2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication2/Models/Item.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Itemname { get; set; }

        [Required]
        public int Price { get; set; }
    }
}

WebApplication2/Models/UserRegistration.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    public class UserRegistration
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

WebApplication2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult Index()
        {
            return View();
        }

       /* public IActionResult Table()
        {
            return View();
        }*/
        public IActionResult Kitchen()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Blogs()
        {
            return View();
        }





        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication2/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ItemController : Controller
    {
        private DatabaseContext _contxt;

        public ItemController(DatabaseContext context)
        {
            _contxt = context;
        }

        public IActionResult Index()
        {
            var items = _contxt.products.ToList(); //select *from products
            return View(items);
        }
         public IActionResult Tablecontent()
          {
              var item = _contxt.products.ToList();
              return View(item);
          }
      
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Item it)
        {
            if (ModelState.IsValid)
            {
                var i = new Item()
                {
                    Itemname = it.Itemname,
                    Price = it.Price,


                };
                _contxt.products.Add(i);//insert the data
                _contxt.SaveChanges();
                TempData["msg"] = "created";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Some error occured";
                return View();
            }

        }
        public IActionResult Remove(int id)
        {
            var it = _contxt.products.SingleOrDefault(i => i.Id == id);   //select * from products where id ='id
            _contxt.products.Remove(it);
            _contxt.SaveChanges();
            TempData["msg"] = "successfully removed";
            return RedirectToAction("Index");
        }
       
        public IActionResult Edit(int id)
        {
            var it = _contxt.products.SingleOrDefault(i => i.Id == id);
            return View(it);
        }
        [HttpPost]
        public IActionResult Edit(Item i)
        {
            if (ModelState.IsValid)
            {
                _contxt.products.Update(i);
                _contxt.SaveChanges();
                TempData["msg"] = "successfully updated";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Some error occured";
                return View();
            }
        }
        

    }
}

WebApplication2/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;
namespace WebApplication2.Controllers
{
    public class LoginController : Controller
    {
      

        public IActionResult Signup()
        {
            return View();
        }
        public IActionResult login()
        {
            return View();
        }


    }
    
}

WebApplication2/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication2.Controllers
{
    public class TableController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        /* public IActionResult Tablecontent()
         {
             return View();
         }
        */
        public IActionResult Add(int id)
        {

            return View();
        }
    }
}

WebApplication2/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About page";
}
<section class='body-section'>
    <h3>About Us</h3>
    <p>The Village Restro, an initiative of SABAH Nepal (SAARC Business Association of Home Based Workers) is not only serving
        delicious food for you to savor but also helping hundreds of women earn their livelihood through the involvement in 
        the production,processing and cooking of food. SABAH Nepal’s skill enhancement training on cooking and hygiene coupled 
        with their inherited traditional skills has enabled these home based workers to cook like professionals. 
        SABAH Nepal (SAARC Business Association of Home Based Workers) works towards strengthening the livelihoods of
        women home based workers.

<h4>Farm to table</h4>

We source fresh organic ingredients directly from the small farms of our community members.  Food is also hygienically prepared by our trained members without using MSG or any other pre-processed ingredients and food additives.
SABAH Nepal’s skill enhancement training on cooking and hygiene coupled with their inherited traditional skills has enabled these home based workers to cook like professionals.

</p>
<h4>Restaurant Amenities</h4>
<ul>
    <li>Free WiFi</li>
    <li>Smoking Zone</li>
    <li>Live Music</li>
    <li>Parking</li>
</ul>
</section>
<footer class='footers'>
 
</footer>

WebApplication2/Views/Home/Blogs.cshtml
@{
    ViewData["Title"] = "Blogs Page";
}
<section class='body-section'>
<p>
<h4>Modern Restaurant Management</h4>

Modern Restaurant Management is the go-to resource for on-the-go restaurant professionals. 
As the name suggests, the popular restaurant blog covers everything from recent management 
news and trends to expert advice from industry veterans.Unlike many restaurant blogs, the 
publication focuses specifically on the business of food. You won’t find menu ideas or trending
desserts here. Restaurant owners and managers look to the blog for actionable advice for 
improving restaurant operations and efficiency.
</p>
<p><h4>Restaurant Den</h4>
Restaurateurs know that marketing is more than throwing up a website and telling your friends about 
your local hot spot, so owners turn to Restaurant Den to learn the latest marketing tactics that get
guests in the door, like social media marketing, email strategies, list building techniques, search engine
optimization (SEO) and more.</p>
<p>
    <h4>Restaurant Engine</h4>
Restaurant Engine teaches business owners about the benefits of using a digital menu board, top software integrations, online ordering set up and more.

Restaurants need more than a simple “About Us” page to make an impact online. Customers expect to find menus, reviews and convenient online ordering options. It’s about creating an exceptional digital experience. Meet the demands of the modern foodie by following the advice in this blog.

<h4>Restaurant Manifesto</h4>
The Restaurant Manifesto gives readers the tools to create a flawless dining experience from the point of view of the guests, as the publication is written by conscientious diners. Readers will come away with actionable strategies for table talk, bar service and more. This restaurant blog believes that a better dining experience “will result in better service and more successful meals.”

Smart management and a stellar marketing strategy aren’t the only ingredients for success. The dining experience must also be a top priority for restaurant management. Positive experiences keep customers coming back for more. Not to mention, repeat customers cost less to acquire than new customers.

<h4>The Restaurant Expert</h4>
Your success as a business comes down to your bottom line. The Restaurant Expert helps restaurant owners manage cash flow to maximize profits. Learn how to implement money management systems by exploring topics such as menu pricing, cost calculations and software solutions.

<h4>Uncorkd</h4>
If you run a bar or serve alcohol, check out Uncorkd. This popular blog helps restaurant leaders improve beverage operations, stay on top of wine trends, create holiday cocktails and more. Readers also turn to these beverage connoisseurs for advice on liquor costs, upsell techniques and bar inventory management.

The Uncorkd mission is to “revolutionize the way people think about, purchase, and enjoy drinks in a restaurant.” Read up on popular topics to improve your restaurant or bar’s beverage game.
</p>
</section>

WebApplication2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

 
  <section class='body-section'>
    <h2 style='text-align:center;color:#6C757D;'>
        Tap on <a class="navbar-icon"  asp-controller="Item" asp-action="Tablecontent">+</a>to continue
    </h2>
   </section>

WebApplication2/Views/Home/Kitchen.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<section class='body-section'>
<section  class='container-fluid mt-5 ' >
    <h3>ORDER</h3>
    <h4>TABLE NO:<span style='margin-right:2px'>1</span></h4>
    
        <article id='order'>
              <h5>Strawberry Icecream</h5>
              <h6 style='margin-top:-10px'>Rs.150</h6>
          </article>
          <div class="total" style='float:right'><h4>TOTAL:RS.<span id="total">0</span></h4></div>
</section>
</section>

WebApplication2/Views/Home/Table.cshtml
@{
    ViewData["Title"] = "Table";
}
<!------------------<section class='body-section'>
     <header class='d-flex justify-content-end'>
        <h5 class='text-white'>Reserved</h5>
        <div class="reserved-item"></div>
        &nbsp;&nbsp;
        <h5 class='text-white'>Available</h5>
        <div class="available-item"></div>
    </header>
<nav class="navbar my-3" style="border:0.5px solid white">
   
  <form class="container-fluid">
    <div class="input-group">
      <input type="search" id='mySearch' class="form-control" placeholder="Choose table"  onkeyup="myFunction()">
    </div>
  </form>
</nav>
<section class='table-center'>
   
       <div class="grid-container" id='myDiv'>
       <a ><div class="grid-item">T1</div></a>
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">B2</div></a>
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">T3</div> </a>  
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">A4</div></a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">T5</div></a>
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">B6</div> </a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">A7</div></a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">C8</div></a>
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">T9</div> </a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">A10</div></a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">A9</div> </a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">T8</div> </a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">A1</div></a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">B4</div> </a> 
        <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">A68</div> </a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">C2</div></a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">T6</div> </a> 
        <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">C8</div></a> 
       <a asp-controller="Item" asp-action="Tablecontent"><div class="grid-item">B1</div> </a> 
   
        </div>

    
  

</section>
</section>

------------------->

WebApplication2/Views/Item/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@model WebApplication2.Models.Item;
<div class="row justify-content-md-center ">
     <div class="col-6">
            <h4 class="text-center text-white">CREATE ITEM</h4>
            @if(TempData["error"] is not null){
                <div class="alert alert-danger">@TempData["error"]</div>
            }
             @if(TempData["msg"] is not null){
                <div class="alert alert-success">@TempData["msg"]</div>
            }
            <hr/>
            <form method="post"  asp-controller="Item" asp-action="Create">
                <div class='mb-3 text-white'>
                    <label class='form-label' asp-for="Itemname"></label>
                    <input asp-for="Itemname" class="form-control"/>
                    <span class="text-danger" asp-validation-for="Itemname"></span>
                </div>
                 <div class='mb-3 text-white'>
                    <label class='form-label' asp-for="Price"></label>
                    <input asp-for="Price" class="form-control"/>
                    <span class="text-danger" asp-validation-for="Price"></span>
                </div>
               
                <hr />
               <button type="submit" class="btn btn-success">Create</button>
             
            </form>
             
        </div>
    </div>

WebApplication2/Views/Item/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@model WebApplication2.Models.Item;
<div class="row justify-content-md-center">
     <div class="col-6">
            <h3 class="text-center text-white">EDIT ITEM</h3>
            @if(TempData["error"] is not null){
                <div class="alert alert-danger">@TempData["error"]</div>
            }
             @if(TempData["msg"] is not null){
                <div class="alert alert-success">@TempData["msg"]</div>
            }
            <hr/>
            <form method="post"  asp-controller="Item" asp-action="Edit">
                <input type="hidden" asp-for="Id"/>
                <div class='mb-3 text-white'>
                    <label class='form-label' asp-for="Itemname"></label>
                    <input asp-for="Itemname" class="form-control"/>
                    <span class="text-danger" asp-validation-for="Itemname"></span>
                </div>
                 <div class='mb-3 text-white'>
                    <label class='form-label' asp-for="Price"></label>
                    <input asp-for="Price" class="form-control"/>
                    <span class="text-danger" asp-validation-for="Price"></span>
                </div>
               
                <hr />
               <button type="submit" class="btn btn-success">Edit</button>
             
            </form>
             
        </div>
    </div>

WebApplication2/Views/Item/Index.cshtml
@{
    ViewData["Title"] = "All Items";
}
@model IEnumerable<WebApplication2.Models.Item>
<div class="row justify-content-md-center admin-center">
     <div class="col-8">
         <h3 class="text-center">ALL ITEMS</h3>
         <a class="btn btn-primary" asp-controller="Item" asp-action="Create">Create</a>
         <hr/>
            @if(TempData["error"] is not null){
                <div class="alert alert-danger">@TempData["error"]</div>
            }
             @if(TempData["msg"] is not null){
                <div class="alert alert-success">@TempData["msg"]</div>
            }

   <table style="width:100%" class='table table-border'>
    <th>Item list</th>
     <th>Price</th>
    <th>Update</th>
               <tbody>
                    @foreach(var i in Model)
                    {
                    <tr>
                      <td>
                      <h6>@i.Itemname</h6>
                     </td>
                     <td><h6>Rs @i.Price</h6></td> 
                     <td>
                     <a class="btn btn-primary" asp-controller="Item" asp-action="Edit" asp-route-id="@i.Id">Edit</a> |
                     <a class="btn btn-danger" asp-controller="Item" asp-action="Remove" asp-route-id="@i.Id">Remove</a>
                     </td>
                     </tr>
                    }
               </tbody> 
                
</table>
         
        </div>
    </div>

WebApplication2/Views/Item/Tablecontent.cshtml
@{
    ViewData["Title"] = "Table Content";
    }
    @model IEnumerable<WebApplication2.Models.Item>
<html>
   <head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/all.css"  asp-append-version="true">
   </head>

    <body>
        
<main class='body-section'>
    
<header>
    <div style="background-color:yellow;color:black; text-align:center; padding:10px;">
        <h3>MENU ITEMS</h3>
       <span id='notifybtn'>0</span>
       <a href='#order' id='orderbtn'>  ORDER </a>
    </div>
</header>

  <!---<div class="tab-content" id="pills-tabContent" style="margin-top:20px;">
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">------>
<section class='container-fluid' id='menuList' style="margin-top:20px;">
     <div class='row'>
            @foreach(var i in Model)
            {
 <div class='col d-flex' id='menu-item'>
<img src='~/img/image1.jpg' alt='image1'/>
<div id='descriptionDiv'>
    <h5>@i.Itemname</h5>
    <h6>Rs.@i.Price</h6>
    <button class='btnn' id='add'>Add</button>
</div>
</div> 
 }</div>
</section>
<div class='cart-overlay' id='order'>
   <div class='cart-item d-flex justify-content-between'>
    <h5>Itemname</h5>
    <h5> Quantity</h5>
   </div>
  
<div class="total" style='float:right'>
 <h4>TOTAL:RS.<span id="total">0</span></h4>
 </div>
 <div class='my-4'>
     <button class='btn btn-dange' id='clear'>clear order</button>
     <button class='btn btn-success'>purchase</button>
 </div>
 </div>
 </main>
  <script>
 (function(){
   let addbtn = document.querySelectorAll('#add')
   addbtn.forEach(function(btn){
       btn.addEventListener('click',function(event){
           let newName = event.target.previousElementSibling.previousElementSibling.textContent;
           let newPrice= event.target.previousElementSibling.textContent;
           let finalPrice = newPrice.slice(3).trim()
         const item ={}
           item.name = newName;
           item.price = finalPrice;
           console.log(newName)
           console.log(item)
           const cartItem = document.createElement('div')
           cartItem.classList.add('newDiv','d-flex')
           cartItem.innerHTML=`
           <div class='cart-content'>
           <h6>${item.name}</h6>
           <h6 class='cart-item-price'>${item.price}</h6> 
           </div>
           <div class='d-flex justify-content-between'>
           <input type='number' class='input'/>
           <button class=' remove'>remove</button>
           </div>
            <hr/>

 `

   const cart = document.getElementById('order')       
   const total = document.querySelectorAll('.total')   
   cart.insertBefore(cartItem,cart.children[1])
   
   alert('item added')
     showTotals();   
    let clear = document.getElementById('clear')
    clear.addEventListener('click',function(){
    cartItem.innerHTML=''
    document.getElementById('total').textContent=0
    document.getElementById('notifybtn').textContent=0;
   })
  
   })
   })
   function showTotals(){
      
       const total =[];
       const items = document.querySelectorAll('.cart-item-price')
       items.forEach(function(item){
       total.push(parseFloat(item.textContent));
       })
       const totalPrice = total.reduce(function(total,item){
           total+= item;
           return total;
       },0)
       const finalTotalPrice = totalPrice.toFixed(2);
       document.getElementById('total').textContent= finalTotalPrice;
       document.getElementById('notifybtn').textContent=total.length;

   }
   

 })();
 
 
 
  let cartOverlay = document.getElementById('order')
  let orderbtn = document.getElementById('orderbtn')
      orderbtn.addEventListener('click',function(){
          cartOverlay.classList.toggle('show-cart')
      })
  </script>
 </body>
 </html>

 

WebApplication2/Views/Login/Signup.cshtml
@{
    ViewData["Title"] = "Signup";
}
@model WebApplication2.Models.UserRegistration;
<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-6 border border-dark">
            <h3 class="text-center">Sign Up</h3>
            <hr/>
            @if(TempData["error"] is not null){
                <div class="alert alert-danger">@TempData["error"]</div>
            }
             @if(TempData["msg"] is not null){
                <div class="alert alert-success">@TempData["msg"]</div>
            }
            <form method="post" class="p-3" asp-controller="Login" asp-action="Signup">
                
                 <div class='mb-3'>
                    <label class='form-label' asp-for="Email"></label>
                    <input asp-for="Email" class="form-control"/>
                    <span class="text-danger" asp-validation-for="Email"></span>
                </div>
               <div class='mb-3'>
                    <label class='form-label' asp-for="Password"></label>
                    <input asp-for="Password" class="form-control"/>
                    <span class="text-danger" asp-validation-for="Password"></span>
                </div>
                <br />
                <button type="submit" class="btn btn-success form-control">Sign Up</button>
                <div class="row">
                    <div class="col-md-auto pt-3">
                        <p>Already have an account?</p>
                        <a href="~/Login/login">Login</a>
                    </div>                
                </div>
            </form>
        </div>
    </div>
</div>

WebApplication2/Views/Login/login.cshtml
@{
    ViewData["Title"] = "Login";
}
@model WebApplication2.Models.UserRegistration;
<div class="container pt-5">
  
    <div class="row justify-content-md-center">
        <div class="col-6 border border-dark">
            <h3 class="text-center">ORDER TAKER</h3>
            <hr/>
            <form method="post" class="p-3">
             
                 <div class='mb-3'>
                    <label class='form-label' asp-for="Email"></label>
                    <input asp-for="Email" class="form-control"/>
                    <span class="text-danger" asp-validation-for="Email"></span>
                    </div>
                     <div class='mb-3'>
                    <label class='form-label' asp-for="Password"></label>
                    <input asp-for="Password" class="form-control"/>
                    <span class="text-danger" asp-validation-for="Password"></span>
                    </div>
                <button type="submit" class="btn btn-success form-control">Login</button>
                <div class="row">
                    <div class="col-md-auto pt-3">
                        <p>Don't have an account?</p>
                        <a href="~/Login/signup">Signup</a>
                    </div>                
                </div>
            </form>

        </div>
    </div>
</div>
<footer></footer>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/all.css"  asp-append-version="true">
</head>

<body class='body'>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
               <h3>VillageRestro</h3>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                             <a class="nav-link text-black" asp-area="" asp-controller="Login" asp-action="Signup">Signup</a>
                        </li>
                        <li class="nav-item">
                               <a class="nav-link text-black" asp-area="" asp-controller="Item" asp-action="Index">Dashboard</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
  
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

WebApplication2/Views/Table/Receipt.cshtml
 <div class='d-flex'>
        <div class='col-md-2'>
         <button id='dec'>-</button>
        </div>
        <span class='num mt-2' id='count'>0</span>
        <div class='col-md-8' id='main-content'>
          <article style='margin-left:20px'>
              <h5>Strawberry Icecream</h5>
              <h6 style='margin-top:-10px'>Rs.150</h6>
          </article>
        </div>
        <div class='col-md-2'>
         <button id='inc'>+</button>
        </div>
    </div>